#!/usr/bin/env python3
"""scaffold 一个符合 opencli 规范的新 CLI 项目骨架。

输出:
  <name>/
  ├── README.md
  ├── bin/<name>             # bash 调度器
  ├── scripts/
  │   ├── _lib.py
  │   ├── describe.py        # opencli schema
  │   └── version.py
  └── INTERFACE.md           # 命令树规范文档

模板:Python(默认)/ Node / Go(后续可加)。

用法:
  code-skills cli-init <name> [--lang python|node|go] [--force]
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import (  # noqa: E402
    EXIT_OK,
    EXIT_RUNTIME,
    EXIT_USAGE,
    ERR_TARGET_EXISTS,
    ERR_USAGE,
    emit_err,
    emit_ok,
    parse_common_flags,
)


PYTHON_DESCRIBE = '''#!/usr/bin/env python3
"""Output the opencli schema for {name}."""
import json, sys
SCHEMA = {{
    "opencli": "0.1",
    "name": "{name}",
    "version": "0.1.0",
    "description": "TODO: short description",
    "commands": [
        {{"name": "version", "summary": "Print version", "exits": ["0"]}},
        {{"name": "describe", "summary": "Print this schema", "flags": [{{"name": "--json"}}], "exits": ["0"]}},
    ],
    "common_flags": [
        {{"name": "--help", "alias": "-h"}},
        {{"name": "--json"}},
    ],
    "exit_codes": {{"0": "success", "1": "runtime error", "2": "usage error", "3": "missing dependency"}},
}}
if "--json" in sys.argv:
    print(json.dumps(SCHEMA, indent=2))
else:
    print(json.dumps(SCHEMA["commands"], indent=2))
'''


PYTHON_VERSION = '''#!/usr/bin/env python3
print("0.1.0")
'''


PYTHON_LIB = '''"""Shared helpers for {name} CLI."""
EXIT_OK, EXIT_RUNTIME, EXIT_USAGE, EXIT_DEPENDENCY = 0, 1, 2, 3
'''


PYTHON_BIN = '''#!/usr/bin/env bash
# {name} CLI entry (opencli-aligned)
set -e
ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"
CMD="${{1:-help}}"; shift || true
case "$CMD" in
  version|--version|-V) exec python3 "$ROOT/scripts/version.py" "$@" ;;
  describe|schema)      exec python3 "$ROOT/scripts/describe.py" "$@" ;;
  help|-h|--help|"")
    echo "{name} CLI"
    echo ""
    echo "USAGE: bin/{name} <command> [flags]"
    echo ""
    echo "COMMANDS:"
    echo "  version              Print version"
    echo "  describe [--json]    Print opencli schema"
    echo "  help                 This help"
    echo ""
    echo "EXIT CODES:"
    echo "  0 success / 1 runtime / 2 usage / 3 missing dependency"
    ;;
  *)
    echo "Unknown command: $CMD" >&2
    exit 2
    ;;
esac
'''


README_TPL = '''# {name}

> opencli-aligned CLI scaffold generated by `code-skills cli-init`.

## Quick start

```bash
bin/{name} help
bin/{name} version
bin/{name} describe --json
```

## Layout

- `bin/{name}` — entry script
- `scripts/` — sub-command implementations (one .py per command, opencli-style)
- `INTERFACE.md` — full command tree spec

## Next

1. Add real subcommands in `scripts/<verb>.py`
2. Wire them in `bin/{name}` (case branch)
3. Update the SCHEMA in `scripts/describe.py`
4. Document in `INTERFACE.md`
'''


INTERFACE_TPL = '''# {name} · Interface Specification

## Command tree

```
{name}
├── version              Print version
├── describe [--json]    Print opencli schema (machine-readable)
└── help                 Show help
```

## Common flags
- `--help` / `-h` — show help
- `--json` — machine-readable output
- `--quiet` / `-q` — suppress non-error output
- `--verbose` / `-v` — verbose logs
- `--no-color` — disable ANSI colors

## Exit codes
| Code | Meaning |
|------|---------|
| 0 | success |
| 1 | runtime error |
| 2 | usage error |
| 3 | missing dependency |
| 130 | interrupted |

## Error response (JSON mode)
```json
{{
  "ok": false,
  "error": {{ "code": "USAGE_ERROR", "message": "...", "hint": "...", "request_id": "..." }}
}}
```

## TODO
- [ ] add real subcommands
- [ ] document each error code
'''


def scaffold(name: str, force: bool, as_json: bool) -> int:
    target = Path.cwd() / name
    if target.exists() and not force:
        emit_err(
            ERR_TARGET_EXISTS,
            f"directory already exists: {target}",
            "use --force to overwrite",
            as_json,
        )
        return EXIT_RUNTIME

    target.mkdir(parents=True, exist_ok=True)
    (target / "bin").mkdir(exist_ok=True)
    (target / "scripts").mkdir(exist_ok=True)

    (target / "bin" / name).write_text(PYTHON_BIN.format(name=name))
    (target / "scripts" / "_lib.py").write_text(PYTHON_LIB.format(name=name))
    (target / "scripts" / "describe.py").write_text(PYTHON_DESCRIBE.format(name=name))
    (target / "scripts" / "version.py").write_text(PYTHON_VERSION)
    (target / "README.md").write_text(README_TPL.format(name=name))
    (target / "INTERFACE.md").write_text(INTERFACE_TPL.format(name=name))

    # mark executables
    import os
    import stat
    for p in [target / "bin" / name, target / "scripts" / "describe.py", target / "scripts" / "version.py"]:
        st = os.stat(p)
        os.chmod(p, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    if as_json:
        emit_ok({"created": str(target), "files": 6}, as_json=True)
    else:
        print(f"[OK] scaffolded {target}")
        print()
        print("next:")
        print(f"  cd {name}")
        print(f"  ./bin/{name} help")
        print(f"  ./bin/{name} describe --json")
    return EXIT_OK


def main(argv: list[str]) -> int:
    flags, rest = parse_common_flags(argv)
    if flags["help"] or not rest:
        print(__doc__)
        return EXIT_OK
    name = None
    force = False
    lang = "python"
    i = 0
    while i < len(rest):
        a = rest[i]
        if a == "--force":
            force = True
        elif a == "--lang":
            i += 1
            lang = rest[i] if i < len(rest) else "python"
        elif a.startswith("-"):
            emit_err(ERR_USAGE, f"unknown flag: {a}", "see --help", flags["json"])
            return EXIT_USAGE
        elif name is None:
            name = a
        else:
            emit_err(ERR_USAGE, "extra positional argument", "only <name> is allowed", flags["json"])
            return EXIT_USAGE
        i += 1
    if not name:
        emit_err(ERR_USAGE, "missing <name>", "code-skills cli-init my-cli", flags["json"])
        return EXIT_USAGE
    if lang != "python":
        emit_err(ERR_USAGE, f"language not yet supported: {lang}",
                 "currently only --lang python is supported", flags["json"])
        return EXIT_USAGE
    return scaffold(name, force, flags["json"])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
