#!/usr/bin/env python3
"""把本仓库 15 个 skill 导出为其他 agent 工具能用的格式。

支持的目标格式:
  codex      - OpenAI Codex CLI(AGENTS.md + ~/.codex/skills/<name>.md)
  cursor     - Cursor IDE(.cursor/rules/<name>.mdc,带 cursor-specific frontmatter)
  opencode   - opencode-ai/opencode 终端 agent(.opencode/<name>.md)
  generic    - 纯 markdown(适配 openclaw / Hermes Agent / Trae 等任意 markdown 消费工具)

用法:
  bin/code-skills export <tool> [<output-dir>]
  bin/code-skills export codex                 # 默认输出到 dist/codex/
  bin/code-skills export cursor /path/to/proj  # 输出到 /path/to/proj/.cursor/rules/
  bin/code-skills export generic               # 默认 dist/generic/

退出码: 0 成功 / 1 运行时错 / 2 用法错
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import (  # noqa: E402
    EXIT_OK,
    EXIT_RUNTIME,
    EXIT_USAGE,
    ERR_USAGE,
    discover_skills,
    emit_err,
    emit_ok,
    parse_common_flags,
)

ROOT = Path(__file__).resolve().parent.parent

SUPPORTED_TOOLS = ["codex", "cursor", "opencode", "generic"]


def parse_skill(folder: Path) -> dict:
    """从 SKILL.md 抽 frontmatter + body。"""
    text = (folder / "SKILL.md").read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {"name": folder.name, "description": "", "body": text}
    end = text.find("\n---", 3)
    block = text[3:end].strip()
    body = text[end + 4:].lstrip()
    name = ""
    desc_lines: list[str] = []
    in_desc = False
    for line in block.splitlines():
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip()
            in_desc = False
        elif line.startswith("description:"):
            rest = line.split(":", 1)[1].strip()
            if rest == "|":
                in_desc = True
            else:
                desc_lines.append(rest)
                in_desc = False
        elif in_desc and (line.startswith("  ") or line == ""):
            desc_lines.append(line.strip())
        else:
            in_desc = False
    return {"name": name, "description": "\n".join(desc_lines).strip(), "body": body}


def extract_triggers(description: str) -> list[str]:
    """从描述里抽触发词(中文「」内 + 英文 quotes)。"""
    triggers = re.findall(r"「([^」]+)」|\"([^\"]+)\"|'([^']+)'", description)
    flat = [t for triple in triggers for t in triple if t]
    return list(dict.fromkeys(flat))[:10]


# ------------- codex format -------------
# AGENTS.md(项目级 agents 指令)+ skills 单独文件

def export_codex(out: Path, skills: list[dict]) -> None:
    out.mkdir(parents=True, exist_ok=True)
    skills_dir = out / "skills"
    skills_dir.mkdir(exist_ok=True)

    # 1) AGENTS.md 总入口(简短 index + 触发条件)
    agents_md = ["# AGENTS.md\n",
                 "Generated by code-skills export. Source: https://github.com/tiantangcao1980-web/code-skills\n",
                 "## Available Skills\n"]
    for s in skills:
        triggers = extract_triggers(s["description"])
        agents_md.append(f"### `{s['name']}`")
        # 取 description 第一段
        first_para = s["description"].split("\n\n")[0].strip()
        agents_md.append(first_para)
        if triggers:
            agents_md.append(f"**Triggers**: {', '.join(triggers[:5])}")
        agents_md.append(f"Full skill: [skills/{s['name']}.md](skills/{s['name']}.md)\n")
    (out / "AGENTS.md").write_text("\n".join(agents_md), encoding="utf-8")

    # 2) 每个 skill 单独文件(原 SKILL.md 全文 + Codex header)
    for s in skills:
        content = (
            f"# {s['name']}\n\n"
            f"> Imported from code-skills repo. See AGENTS.md for index.\n\n"
            f"{s['body']}"
        )
        (skills_dir / f"{s['name']}.md").write_text(content, encoding="utf-8")


# ------------- cursor format -------------
# .cursor/rules/<name>.mdc with cursor-specific frontmatter

def export_cursor(out: Path, skills: list[dict]) -> None:
    rules_dir = out / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    for s in skills:
        # Cursor 的 .mdc 格式:frontmatter(globs / alwaysApply / description)+ body
        content = (
            f"---\n"
            f"description: {s['description'].splitlines()[0][:200] if s['description'] else s['name']}\n"
            f"globs:\n"
            f"alwaysApply: false\n"
            f"---\n\n"
            f"# {s['name']}\n\n"
            f"{s['body']}"
        )
        (rules_dir / f"{s['name']}.mdc").write_text(content, encoding="utf-8")
    # README in dist
    (out / "README.md").write_text(
        f"# Cursor Rules · code-skills\n\n"
        f"Generated by `bin/code-skills export cursor`. {len(skills)} skills exported.\n\n"
        f"Drop `.cursor/rules/` into your Cursor project root.\n"
        f"Source: https://github.com/tiantangcao1980-web/code-skills\n",
        encoding="utf-8",
    )


# ------------- opencode format -------------
# opencode-ai/opencode uses .opencode/ directory + JSON config

def export_opencode(out: Path, skills: list[dict]) -> None:
    skills_dir = out / ".opencode" / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)
    for s in skills:
        content = f"# {s['name']}\n\n{s['body']}"
        (skills_dir / f"{s['name']}.md").write_text(content, encoding="utf-8")
    # opencode config snippet
    config = {
        "skills": [{"name": s["name"], "path": f".opencode/skills/{s['name']}.md"}
                   for s in skills],
        "source": "https://github.com/tiantangcao1980-web/code-skills",
    }
    import json
    (out / ".opencode" / "skills.json").write_text(
        json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (out / "README.md").write_text(
        f"# opencode skills · code-skills\n\n"
        f"Generated by `bin/code-skills export opencode`. {len(skills)} skills exported.\n\n"
        f"Copy `.opencode/` into your opencode project root.\n",
        encoding="utf-8",
    )


# ------------- generic format -------------
# Plain markdown — adapter for openclaw / Hermes / Trae / any other tool

def export_generic(out: Path, skills: list[dict]) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for s in skills:
        content = (
            f"---\n"
            f"name: {s['name']}\n"
            f"description: |\n"
        )
        for line in s["description"].splitlines():
            content += f"  {line}\n"
        content += f"---\n\n# {s['name']}\n\n{s['body']}"
        (out / f"{s['name']}.md").write_text(content, encoding="utf-8")
    # README
    triggers_index = []
    for s in skills:
        ts = extract_triggers(s["description"])
        if ts:
            triggers_index.append(f"- **{s['name']}**: {', '.join(ts[:5])}")
    (out / "README.md").write_text(
        f"# Generic Markdown Skills · code-skills\n\n"
        f"Generated by `bin/code-skills export generic`. {len(skills)} skills.\n\n"
        f"Each `.md` file is a self-contained skill. Drop into any markdown-aware\n"
        f"agent tool (openclaw, Hermes Agent, Trae, etc.).\n\n"
        f"## Trigger keyword index\n\n" + "\n".join(triggers_index) + "\n\n"
        f"Source: https://github.com/tiantangcao1980-web/code-skills\n",
        encoding="utf-8",
    )


EXPORTERS = {
    "codex": export_codex,
    "cursor": export_cursor,
    "opencode": export_opencode,
    "generic": export_generic,
}


def main(argv: list[str]) -> int:
    flags, rest = parse_common_flags(argv)
    if flags["help"] or not rest:
        print(__doc__)
        return EXIT_OK

    tool = rest[0]
    if tool not in EXPORTERS:
        emit_err(ERR_USAGE, f"unknown tool: {tool}",
                 f"valid: {', '.join(SUPPORTED_TOOLS)}", flags["json"])
        return EXIT_USAGE

    out = Path(rest[1]) if len(rest) > 1 else (ROOT / "dist" / tool)
    out = out.resolve()

    skills_names = discover_skills(ROOT)
    skills = [parse_skill(ROOT / n) for n in skills_names]

    # Clean output
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)

    EXPORTERS[tool](out, skills)

    files_written = sum(1 for _ in out.rglob("*") if _.is_file())
    if flags["json"]:
        emit_ok({
            "tool": tool,
            "output_dir": str(out),
            "skills_exported": len(skills),
            "files_written": files_written,
        }, as_json=True)
    else:
        print(f"[OK] exported {len(skills)} skills to {out}")
        print(f"     files: {files_written}")
        print(f"     tool: {tool}")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
